title: "wzgit" # title on the main page
database:
  type: "sqlite" # supported : sqlite(doesn't require cgo), sqlite3, mysql
  url: "wzgit.db" # connection string or sqlite3 database path

git:
  http:
    enabled: true # serve git repositories using http
    https: false # show https instead of http in the repository pages
    domain: "localhost:5555" # domain displayed for the http git server
    address: "0.0.0.0" # address to listen on
    port: 5555 # bind port for http git request
  ssh:
    enabled: false # serve git repositories using ssh
    domain: "localhost:2222" # domain displayed for the ssh git server
    address: "0.0.0.0" # address to listen on
    port: 2222 # bind port for ssh git request
    key: "ssh.key" # private key
  path: "./repos" # path to repositories directory
  public: true # allow non-registered users to see public repositories
  maximumCommits: 100 # maximum number of commits shown on log pages

ldap:
  enabled: false # logging using ldap credential
  url: "ldaps://ldap.example.com" # url to the ldap server
  attribute: "cn" # attribute associated with the username
  binding: "ou=users,dc=example,dc=com"

users:
  registration: true # allow registration, will be disabled if ldap is enabled

protection:
  ip: 10 # Maximum connection attempts before the ip is blocked
  account: 50 # Maximum connection attempts before the account is blocked
  registration: 5 # Maximum number of registration per ip
  reset: 120 # Number of seconds before clearing the block on ip/accounts
